# Numpy Tutorial

In [39]:
import numpy as np

In [40]:
X = np.array([1, 2, 3])
print(X)

[1 2 3]


In [41]:
type(X)

numpy.ndarray

In [42]:
l = [4, 5, 10]
X = np.asarray(l)
type(X)

numpy.ndarray

In [43]:
X

array([ 4,  5, 10])

In [44]:
X = np.asarray(l, float)
print(X)

[ 4.  5. 10.]


In [45]:
X.shape

(3,)

In [46]:
np.array?

In [47]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
X.shape

(2, 3)

In [50]:
X[1,2]

6

In [51]:
X[0, 0:2]

array([1, 2])

In [52]:
X[0, :]

array([1, 2, 3])

In [53]:
X = np.zeros((4, 5))

In [54]:
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
X = np.eye(4, 4)
X

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
X = np.random.random((4, 5))
X

array([[0.86890036, 0.68463593, 0.90935225, 0.66118583, 0.85691438],
       [0.38605138, 0.83506118, 0.0040744 , 0.8461973 , 0.3452414 ],
       [0.49364878, 0.93594335, 0.01732522, 0.13113627, 0.6949154 ],
       [0.70304154, 0.83057278, 0.7217721 , 0.81899172, 0.85187   ]])

In [57]:
Z = X.T

In [58]:
Z

array([[0.86890036, 0.38605138, 0.49364878, 0.70304154],
       [0.68463593, 0.83506118, 0.93594335, 0.83057278],
       [0.90935225, 0.0040744 , 0.01732522, 0.7217721 ],
       [0.66118583, 0.8461973 , 0.13113627, 0.81899172],
       [0.85691438, 0.3452414 , 0.6949154 , 0.85187   ]])

In [59]:
Y = X.reshape(20, 1)

In [60]:
Y

array([[0.86890036],
       [0.68463593],
       [0.90935225],
       [0.66118583],
       [0.85691438],
       [0.38605138],
       [0.83506118],
       [0.0040744 ],
       [0.8461973 ],
       [0.3452414 ],
       [0.49364878],
       [0.93594335],
       [0.01732522],
       [0.13113627],
       [0.6949154 ],
       [0.70304154],
       [0.83057278],
       [0.7217721 ],
       [0.81899172],
       [0.85187   ]])

In [77]:
A = np.arange(5)
print(A)

[0 1 2 3 4]


In [78]:
B = np.arange(5)

In [63]:
C = A + B
D = A - B
E = A * B
print(C, D, E)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [64]:
print(A, A + 1)

[0 1 2 3 4] [1 2 3 4 5]


In [65]:
A = np.random.random((2, 3))
print(A)
print(A + 1)

[[0.03307037 0.73385693 0.75032487]
 [0.35411434 0.49672018 0.00492496]]
[[1.03307037 1.73385693 1.75032487]
 [1.35411434 1.49672018 1.00492496]]


In [84]:
A = np.floor(np.random.random((2, 3))*10)
print(A)

[[9. 0. 6.]
 [1. 0. 6.]]


In [85]:
u = [1, 2, 3]
v = [-1, 0, 1]

p1 = np.inner(u, v)
print(p1)

2


In [68]:
p2 = np.outer(u, v)
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [69]:
A = np.ones((2, 3))
B = np.ones((3, 2))
np.dot(A, B)

array([[3., 3.],
       [3., 3.]])

In [70]:
np.dot(B.T, A.T)

array([[3., 3.],
       [3., 3.]])

In [71]:
A = np.ones((2, 3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [72]:
A.sum()

6.0

In [73]:
a=A.sum(axis=0)
b=A.sum(axis=1)

In [74]:
a,b

(array([2., 2., 2.]), array([3., 3.]))

In [75]:
A.max()

1.0

In [86]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a_dot_b=np.dot(a,b)

In [87]:
a_dot_b

30

In [102]:
a=[1,2,3,4,5]
print(np.diag(a))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [106]:
d = np.arange(5)  # just like range() 
print(d) 

d[1] = 9.7 
print(d)  # arrays keep their type even if elements changed 

print(d*0.4)  # operations create a new array, with new type 

d = np.arange(5, dtype=np.float)  
print(d) 

np.arange(3, 7, 0.5)  # arbitrary start, stop and step 


[0 1 2 3 4]
[0 9 2 3 4]
[0.  3.6 0.8 1.2 1.6]
[0. 1. 2. 3. 4.]


array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [108]:
np.arange(4.0)

array([0., 1., 2., 3.])

# Pandas

In [111]:
import pandas as pd

In [113]:
df = pd.read_csv('mobile_clean.csv')

In [114]:
df.head()

sim_type  aperture  gpu_rank  weight  stand_by_time  processor_frequency  \
0         0        12        55   155.0            250                  1.3   
1         0         1        55   132.0            300                  1.3   
2         0         9        55   142.0            329                  1.5   
3         0         8        55   152.0            385                  1.3   
4         1         1        55   234.0            385                  1.3   

   thickness  flash_type  front_camera_resolution  auto_focus    ...     \
0       10.5           5                     2.00           0    ...      
1       10.6           5                     0.30           1    ...      
2        8.5           5                     2.00           3    ...      
3        8.0           5                     2.00           3    ...      
4        7.9           5                     1.92           3    ...      

   micro_sd_slot  screen_pixel_density  water_proof_rate  phone_width  \
0              4                     2                 3         67.8   
1              4                     4                 6         64.0   
2              4                     9                 6         72.0   
3              4                     1                 3         75.1   
4              4                     1                 6         91.0   

   expandable_memory  version  usb_type  battery_capacity  processor_rank  \
0               64.0        5         3              2000             125   
1               32.0        5         3              2000             165   
2               32.0        6         3              2500             164   
3               32.0        6         3              3000             165   
4               32.0        6         3              3000             165   

   is_liked  
0         1  
1         1  
2         0  
3         1  
4         0  

[5 rows x 40 columns]

In [115]:
type(df)

pandas.core.frame.DataFrame

In [117]:
df.tail(5)

sim_type  aperture  gpu_rank  weight  stand_by_time  processor_frequency  \
104         3        10        14   192.0            540                  1.8   
105         0         5         3   157.0            400                  2.3   
106         3        10         6   192.0            384                  1.8   
107         3        10        12   129.0            250                  1.4   
108         2         8         3   158.0            400                  2.2   

     thickness  flash_type  front_camera_resolution  auto_focus    ...     \
104        9.4           2                      2.0           2    ...      
105        7.7           5                      5.0           3    ...      
106        7.3           2                      5.0           3    ...      
107        6.9           2                      1.2           3    ...      
108        7.4           6                      8.0           3    ...      

     micro_sd_slot  screen_pixel_density  water_proof_rate  phone_width  \
104              4                    29                 6         77.2   
105              6                    27                 1         72.6   
106              1                    16                 6         77.9   
107              1                    13                 6         67.0   
108              5                    16                 6         74.7   

     expandable_memory  version  usb_type  battery_capacity  processor_rank  \
104              256.0        6         3              3410               8   
105              200.0        9         3              3600             101   
106                0.0       14        13              2750               1   
107                0.0       12        13              1810               7   
108                0.0       10        12              3000               2   

     is_liked  
104         1  
105         1  
106         1  
107         1  
108         0  

[5 rows x 40 columns]

In [119]:
df.loc[0] #loc is used to access any particular row

sim_type                                0.0
aperture                               12.0
gpu_rank                               55.0
weight                                155.0
stand_by_time                         250.0
processor_frequency                     1.3
thickness                              10.5
flash_type                              5.0
front_camera_resolution                 2.0
auto_focus                              0.0
screen_size                             4.5
frames_per_second                      15.0
FM                                      3.0
no_of_reviews_in_gsmarena_in_week       0.0
os                                      0.0
phone_height                          132.9
screen_protection                      26.0
sim_size                                3.0
price                                3870.0
talk_time                               9.0
video_resolution                      480.0
display_resolution                     12.0
removable_battery               

In [121]:
df_short=df[10:30]
df_short.shape

(20, 40)

In [122]:
df_thin = df[['stand_by_time', 'expandable_memory', 'price', 'battery_capacity', 'is_liked']]

In [123]:
df_thin

stand_by_time  expandable_memory  price  battery_capacity  is_liked
0              250               64.0   3870              2000         1
1              300               32.0   4059              2000         1
2              329               32.0   4777              2500         0
3              385               32.0   5799              3000         1
4              385               32.0   5990              3000         0
5              280               32.0   5999              2900         0
6              230              128.0   5999              1700         1
7              182               32.0   6599              2000         1
8              182               32.0   6599              2000         1
9              435               32.0   6649              3000         1
10             514               32.0   6749              4000         1
11             300              128.0   6990              2600         0
12             280               32.0   6999              2500         1
13             198               32.0   6999              2200         1
14             200               32.0   6999              2500         1
15             680              256.0   6999              2500         1
16             576              128.0   7340              2200         1
17             264               32.0   7499              2300         1
18             180              128.0   7590              2000         1
19             160               32.0   7790              2230         1
20             450               32.0   7899              4000         1
21             264               32.0   7914              2900         1
22             354              128.0   7999              2400         0
23             345                0.0   8490              2000         1
24             322               32.0   8499              2750         1
25             914               64.0   8999              5000         1
26             456              128.0   8999              3000         1
27             350               64.0   8999              3000         1
28             617               32.0   9399              2100         1
29             775               32.0   9499              3100         1
..             ...                ...    ...               ...       ...
79             180              128.0  24900              2900         1
80             598                0.0  24999              3000         0
81             410              128.0  24999              3000         1
82             590              128.0  25500              2930         1
83             504              200.0  25500              2600         0
84             250              128.0  27580              2850         1
85             200              128.0  29900              3220         1
86             420               64.0  29990              3200         1
87             410             2048.0  30947              3000         1
88             440                0.0  31999              3450         1
89             354                0.0  33900              2550         1
90             500                0.0  34999              3760         0
91             240                0.0  34999              1624         0
92             360                0.0  35900              2700         1
93             250                0.0  36499              1810         1
94             250                0.0  36999              1810         1
95             580              256.0  37766              2840         0
96             410               32.0  38000              3000         1
97             340              256.0  39890              2900         1
98             362               64.0  40900              2600         1
99             250                0.0  48329              1810         1
100            242              200.0  48900              3000         1
101            240                0.0  49499              1715 

In [125]:
df_liked = df_thin[df_thin['is_liked'] == 1]
df_liked.shape

(92, 5)

In [126]:
df_thin['price'].describe()

count      109.000000
mean     19373.211009
std      14039.197220
min       3870.000000
25%       8999.000000
50%      14614.000000
75%      24999.000000
max      64500.000000
Name: price, dtype: float64

In [127]:
df_thin.describe()

stand_by_time  expandable_memory         price  battery_capacity  \
count      109.00000         109.000000    109.000000        109.000000   
mean       404.66055         104.513761  19373.211009       2841.779817   
std        176.44206         275.799767  14039.197220        655.003963   
min        160.00000           0.000000   3870.000000       1560.000000   
25%        264.00000           0.000000   8999.000000       2470.000000   
50%        360.00000          32.000000  14614.000000       2900.000000   
75%        500.00000         128.000000  24999.000000       3100.000000   
max       1093.00000        2048.000000  64500.000000       5000.000000   

         is_liked  
count  109.000000  
mean     0.844037  
std      0.364496  
min      0.000000  
25%      1.000000  
50%      1.000000  
75%      1.000000  
max      1.000000

In [128]:
df_thin[df_thin['is_liked'] == 1]['price'].mean()

19393.239130434784

In [129]:
df_thin[df_thin['is_liked'] == 0]['price'].mean()

19264.823529411766

In [130]:
g = df_thin.groupby(['is_liked'])

In [131]:
g

In [132]:
for key, df_key in g:
  print(key)
  print(df_key)

0
     stand_by_time  expandable_memory  price  battery_capacity  is_liked
2              329               32.0   4777              2500         0
4              385               32.0   5990              3000         0
5              280               32.0   5999              2900         0
11             300              128.0   6990              2600         0
22             354              128.0   7999              2400         0
38             490               32.0   9999              2100         0
53             345               64.0  14300              2950         0
60             840                0.0  15689              4100         0
74             390              128.0  21999              2800         0
77             620              128.0  22999              3100         0
78             618                0.0  24499              3600         0
80             598                0.0  24999              3000         0
83             504              200.0  25500     

In [133]:
df_thin.groupby(['is_liked']).describe()

battery_capacity  expandable_memory         price  \
is_liked                                                            
0        count         17.000000          17.000000     17.000000   
         mean        2874.941176          68.235294  19264.823529   
         std          591.777035          79.100829  11172.690423   
         min         1624.000000           0.000000   4777.000000   
         25%         2600.000000           0.000000   7999.000000   
         50%         2900.000000          32.000000  21999.000000   
         75%         3000.000000         128.000000  25500.000000   
         max         4100.000000         256.000000  37766.000000   
1        count         92.000000          92.000000     92.000000   
         mean        2835.652174         111.217391  19393.239130   
         std          668.850998         298.134413  14559.162189   
         min         1560.000000           0.000000   3870.000000   
         25%         2457.500000          32.000000   9299.000000   
         50%         2900.000000          32.000000  14124.000000   
         75%         3100.000000         128.000000  24924.750000   
         max         5000.000000        2048.000000  64500.000000   

                stand_by_time  
is_liked                       
0        count      17.000000  
         mean      457.235294  
         std       157.094927  
         min       240.000000  
         25%       345.000000  
         50%       400.000000  
         75%       580.000000  
         max       840.000000  
1        count      92.000000  
         mean      394.945652  
         std       178.876246  
         min       160.000000  
         25%       258.250000  
         50%       354.000000  
         75%       482.000000  
         max      1093.000000

In [134]:
x=df.iloc[:,:-1]

In [135]:
x.head()

sim_type  aperture  gpu_rank  weight  stand_by_time  processor_frequency  \
0         0        12        55   155.0            250                  1.3   
1         0         1        55   132.0            300                  1.3   
2         0         9        55   142.0            329                  1.5   
3         0         8        55   152.0            385                  1.3   
4         1         1        55   234.0            385                  1.3   

   thickness  flash_type  front_camera_resolution  auto_focus       ...        \
0       10.5           5                     2.00           0       ...         
1       10.6           5                     0.30           1       ...         
2        8.5           5                     2.00           3       ...         
3        8.0           5                     2.00           3       ...         
4        7.9           5                     1.92           3       ...         

   no_of_cores  micro_sd_slot  screen_pixel_density  water_proof_rate  \
0            6              4                     2                 3   
1            6              4                     4                 6   
2            6              4                     9                 6   
3            6              4                     1                 3   
4            6              4                     1                 6   

   phone_width  expandable_memory  version  usb_type  battery_capacity  \
0         67.8               64.0        5         3              2000   
1         64.0               32.0        5         3              2000   
2         72.0               32.0        6         3              2500   
3         75.1               32.0        6         3              3000   
4         91.0               32.0        6         3              3000   

   processor_rank  
0             125  
1             165  
2             164  
3             165  
4             165  

[5 rows x 39 columns]

In [136]:
type(x)

pandas.core.frame.DataFrame

In [137]:
y=df.iloc[:,-1]

In [140]:
type(x)

pandas.core.frame.DataFrame

In [141]:
y.values

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
      dtype=int64)

# SkLearn

In [142]:
import sklearn.datasets
import numpy as np

In [143]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [144]:
X = breast_cancer.data
Y = breast_cancer.target

In [145]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [146]:
print(X.shape, Y.shape)

(569, 30) (569,)


In [147]:
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

In [148]:
data['class'] = breast_cancer.target
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...    worst texture  worst perimeter  worst area  \
0                 0.07871  ...            17.33           184.60      2019.0   
1                 0.05667  ...            23.41           158.80      1956.0   
2                 0.05999  ...            25.53           152.50      1709.0   
3                 0.09744  ...            26.50            98.87       567.7   
4                 0.05883  ...            16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [149]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension     ...      worst texture  \
count     569.000000              569.000000     ...         569.000000   
mean        0.181162                0.062798     ...          25.677223   
std         0.027414                0.007060     ...           6.146258   
min         0.106000                0.049960     ...          12.020000   
25%         0.161900                0.057700     ...          21.080000   
50%         0.179200                0.061540     ...          25.410000   
75%         0.195700                0.066120     ...          29.720000   
max         0.304000                0.097440     ...          49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483917  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [150]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [151]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [152]:
data.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension           ...             worst radius  \
class                                   ...                            
0                    0.062680           ...                21.134811   
1                    0.062867           ...                13.379801   

       worst texture  worst perimeter   worst area  worst smoothness  \
class                                                                  
0          29.318208       141.370330  1422.286321          0.144845   
1          23.515070        87.005938   558.899440          0.124959   

       worst compactness  worst concavity  worst concave points  \
class                                                             
0               0.374824         0.450606              0.182237   
1               0.182673         0.166238              0.074444   

       worst symmetry  worst fractal dimension  
class                                           
0            0.323468                 0.091530  
1            0.270246                 0.079442  

[2 rows x 30 columns]

# Train Test Split


In [156]:
from sklearn.cross_validation import train_test_split

In [157]:
X = data.drop('class', axis=1)
Y = data['class']

In [158]:
type(X)

pandas.core.frame.DataFrame

In [159]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

In [160]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (426,) (143,)


In [161]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)


In [162]:
print(Y.mean(), Y_train.mean(), Y_test.mean())

0.6274165202108963 0.6328125 0.5789473684210527


In [163]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, stratify = Y)